url: http://github.danielbello.com.ve
title: Proyectos en github
author: Daniel Bello
email: danielbello.hosting@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  programación con código abierto.

theme: minima
# social links
twitter_username: danielbellofoto # DO NOT include the @ character, or else the build will fail!
github_username:  dbellogithub # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
